### ISSUE TITLE
Add edit feature for emergency contacts

### ISSUE THREAD

**Issue by priyalbhatewara123** [priyalbhatewara123/SHE--Live-Without-Fear#17]
By using edit option the user can edit both the name and the number of that contact and it should change the data in SQLite also.

**Comment by MayankUjawane** [comment]
I would like to work on this issue.

**Comment by codeDamon** [comment]
Did you @MayankUjawane still want to work on this issue?
If yes, assign him this issue @priyalbhatewara123 or I can work on this.

**Comment by priyalbhatewara123** [comment]
@MayankUjawane commented first, so I'll assign him after his previous PR gets merged. 
@codeDamon You can create your own issue if you find any bug or feature that can enhance the app.

**Comment by codeDamon** [comment]
> @MayankUjawane commented first, so I'll assign him after his previous PR gets merged.
> @codeDamon You can create your own issue if you find any bug or feature that can enhance the app.

Yeah, no problem. Assign him :)
