### ISSUE TITLE
Add a check if the contact number contains 10 digits 

### ISSUE THREAD

**Issue by priyalbhatewara123** [priyalbhatewara123/SHE--Live-Without-Fear#19]
While registering an emergency contact , the contact number entered by the user should contain 10 digits. If the digits are less than the Edittext should show an error message.

**Comment by TawfikYasser** [comment]
Hello,

I want to help by adding a function to check if digits are less than 10 digits @priyalbhatewara123 

Thanks

**Comment by priyalbhatewara123** [comment]
> Hello,
> 
> I want to help by adding a function to check if digits are less than 10 digits @priyalbhatewara123
> 
> Thanks

Are you a part of JWOC?

**Comment by TawfikYasser** [comment]
No

**Comment by priyalbhatewara123** [comment]
Sorry this issue is for JWOC mentees

**Comment by TawfikYasser** [comment]
Okay, Thanks

**Comment by MayankUjawane** [comment]
I would like to work on this issue Ma'am @priyalbhatewara123

**Comment by priyalbhatewara123** [comment]
> I would like to work on this issue Ma'am @priyalbhatewara123

Assigned :)
