### ISSUE TITLE
Alter the color of the logo

### ISSUE THREAD

**Issue by priyalbhatewara123** [priyalbhatewara123/SHE--Live-Without-Fear#20]
Change the red part of the logo to pink(shade that is used in the app) and blue part to black.

**Comment by AB-san** [comment]
Hello there, I would like to work on this can you please assign this to me.

**Comment by priyalbhatewara123** [comment]
> Hello there, I would like to work on this can you please assign this to me.

Hey! Are you mentee at JWOC?

**Comment by AB-san** [comment]
Yes Discord username- Ansuman Behera#7389

**Comment by priyalbhatewara123** [comment]
Assigned👍

**Comment by AB-san** [comment]
Thank you

**Comment by AB-san** [comment]
Mam u wanted the blue strips to be converted to black ..... so which blue strip - light one or dark one or both??

**Comment by priyalbhatewara123** [comment]
> Mam u wanted the blue strips to be converted to black ..... so which blue strip - light one or dark one or both??

They can be in shades of black. Like one dark and one in light shade.
