### ISSUE TITLE
Implement the search feature in view_contacts activity

### ISSUE THREAD

**Issue by priyalbhatewara123** [priyalbhatewara123/SHE--Live-Without-Fear#21]
Through the search bar user can search for any particular contact. If no such contact exits than it should display "No such contact found. "

**Comment by anushruti11** [comment]
Can I take up this issue?

**Comment by priyalbhatewara123** [comment]
> Can I take up this issue?

Sure :)

**Comment by priyalbhatewara123** [comment]
Hey @anushruti11 Are you still working on this issue? It's been 5 days already.

**Comment by harshita2216** [comment]
I wish to contribute to this issue. (JWoC Mentee)

**Comment by priyalbhatewara123** [comment]
> I wish to contribute to this issue. (JWoC Mentee)

Okay! Go ahead

**Comment by MayankUjawane** [comment]
If this issue is available then I can work on this.

**Comment by MayankUjawane** [comment]
![Screenshot (63)](https://user-images.githubusercontent.com/67855648/108248546-db6d9100-7108-11eb-8aa8-d9f639c30875.png)
![Screenshot (64)](https://user-images.githubusercontent.com/67855648/108248552-dd375480-7108-11eb-880b-ba29bb78b2d0.png)
![Screenshot (65)](https://user-images.githubusercontent.com/67855648/108248554-dd375480-7108-11eb-8b82-973dc8d3c1c3.png)
