### ISSUE TITLE
Improve README.md file

### ISSUE THREAD

**Issue by priyalbhatewara123** [priyalbhatewara123/SHE--Live-Without-Fear#22]
Create a banner for readme. 
Make the readme file more attractive.✨

**Comment by mahmood199** [comment]
Can I take up this issue?

**Comment by priyalbhatewara123** [comment]
> Can I take up this issue?

Sure.

**Comment by priyalbhatewara123** [comment]
What's the progress @mahmood199 ?

**Comment by anubhab1710** [comment]
Hello, @priyalbhatewara123  I would like to contribute to this project by resolving this issue. I have a fair understanding of the project's aim and will be able to create a new banner, additionally improvise the Readme.md file. I request you to kindly assign this issue to me

**Comment by priyalbhatewara123** [comment]
> Hello, @priyalbhatewara123 I would like to contribute to this project by resolving this issue. I have a fair understanding of the project's aim and will be able to create a new banner, additionally improvise the Readme.md file. I request you to kindly assign this issue to me

Assigned :)
