### ISSUE TITLE
Improve UI of the SignUp and Login screen

### ISSUE THREAD

**Issue by priyalbhatewara123** [priyalbhatewara123/SHE--Live-Without-Fear#3]
Change the color theme, add some visuals and improve the UI of the app.

**Comment by MayankUjawane** [comment]
Please assign this to me.

**Comment by MayankUjawane** [comment]
Ma'am for color theme can we make it yellow, and can I replace text views with material text fields. Please give some suggestions to me what type of changes you want.

**Comment by priyalbhatewara123** [comment]
@MayankUjawane for now don't change the color theme.  Modify the edittexts using Android material design. 
You can make the background of signup and login activity white and edittext can be of the color that is used in the background currently.  Rest you can use your own ideas but don't change the color them.

Also send me a screenshot of UI before making a PR. ✨

**Comment by MayankUjawane** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/67855648/106386524-3c1b7080-638a-11eb-978d-e09d6276dd71.png)

**Comment by MayankUjawane** [comment]
is this ok ?

**Comment by MayankUjawane** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/67855648/106387755-07aab300-6390-11eb-9407-45fd1014b0e8.png)

**Comment by priyalbhatewara123** [comment]
1. Black logo doesn't look good. Add the colored one.
2. Login here and register here textviews can be removed.
3. Change the background of edittext to white.
4. Register and login button can have background pink.
5. change the color of Icons before the edittext to pink.

**Comment by MayankUjawane** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/67855648/106388570-fc598680-6393-11eb-95e9-b75e16a026ac.png)
![Screenshot (12)](https://user-images.githubusercontent.com/67855648/106388623-480c3000-6394-11eb-8f21-8a4173e6ec52.png)

**Comment by MayankUjawane** [comment]
which one will be better ?

**Comment by priyalbhatewara123** [comment]
Second one . Without login here

**Comment by MayankUjawane** [comment]
Ok Ma'am

**Comment by MayankUjawane** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/67855648/106389141-c5d13b00-6396-11eb-86c1-10e9275ffdf0.png)

**Comment by MayankUjawane** [comment]
Ma'am can I generate pull request now and please also tell me how to generate a pull request.

**Comment by priyalbhatewara123** [comment]
For pull request refer to [CONTRIBUTING.md](https://github.com/priyalbhatewara123/SHE--Live-Without-Fear/blob/master/CONTRIBUTING.md)
