### ISSUE TITLE
Contacts with same phone number

### ISSUE THREAD

**Issue by codeDamon** [priyalbhatewara123/SHE--Live-Without-Fear#33]
Emergency contacts with same phone number can be added and on deleting anyone of them deletes all of these contacts.

**How to get this bug**
1. Open 'Add Relatives' section in the app.
2. Add a contact
3.  Add another contact with same phone number as previously saved contact.
4. Notice, We can save two contacts with same phone number [BUG]
5. Now, In contact list, try deleting anyone of the contact.
6. Notice, both the contacts with same number deleted. [BUG]

**Why this bug**
* There is no check for the phone number or contact name. Whether already present in the database or not.
* On deleting contact, deletion is done based on phone number. Therefore, deleting one contact deletes all contacts with same phone number.

**How to solve this**
* Add a check before inserting contact into the database, based on phone number.
* Phone number can be made PRIMARY_KEY to limit repetition.
[Note: There may be other better approaches to solve this bug.]

**Comment by priyalbhatewara123** [comment]
I think adding a check while saving a contact would solve this. If the number entered by the user already exists in database then an error message should pop up stating "This number already exists."

**Comment by codeDamon** [comment]
Lets solve few issues :)
Assign it to me
