### ISSUE TITLE
Hard Text Readaibilty 

### ISSUE THREAD

**Issue by codeDamon** [priyalbhatewara123/SHE--Live-Without-Fear#34]
There are few screen in the app where text color are not contrasting with the background, making it difficult to read.

**How to find this**
* Open 'How to use' session. (There may be few more screens with this issue too)
* Text in this screen is hardly visible due to dark purple background.

**How to solve**
* Change the text-color of every TextView where this issue is relevant.

[Note: This issue may be subjective to me only]

**Comment by priyalbhatewara123** [comment]
Only "How to use" activity has purple bg.  We can change the background to some other color . Can you suggest one?

**Comment by codeDamon** [comment]
> Only "How to use" activity has purple bg. We can change the background to some other color . Can you suggest one?

How about just changing the color of the text? I think changing color to white or any light color will do the job.

**Comment by priyalbhatewara123** [comment]
Changing the text color to white works.

**Comment by MayankUjawane** [comment]
Can I work on this issue?

**Comment by priyalbhatewara123** [comment]
> Can I work on this issue?

Sure
Please send a screenshot before making a PR.

**Comment by MayankUjawane** [comment]
![Screenshot (48)](https://user-images.githubusercontent.com/67855648/108203977-0b507080-70d8-11eb-97de-0164248a16eb.png)
![Screenshot (49)](https://user-images.githubusercontent.com/67855648/108203981-0d1a3400-70d8-11eb-983b-81f45420c802.png)
![Screenshot (50)](https://user-images.githubusercontent.com/67855648/108203982-0db2ca80-70d8-11eb-92f7-5135594f6131.png)

**Comment by MayankUjawane** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/67855648/108204091-363ac480-70d8-11eb-91d5-21c8dedc1be5.png)
![Screenshot (52)](https://user-images.githubusercontent.com/67855648/108204097-38048800-70d8-11eb-813b-d2043628e094.png)
![Screenshot (54)](https://user-images.githubusercontent.com/67855648/108204105-38048800-70d8-11eb-81b9-e5b88d4db99b.png)

**Comment by MayankUjawane** [comment]
Which one is better?

**Comment by priyalbhatewara123** [comment]
> Which one is better?

Second one

**Comment by MayankUjawane** [comment]
So can I generate PR for second one?

**Comment by priyalbhatewara123** [comment]
> So can I generate PR for second one?

Yes. 
If you think purple background can be replaced with some other color (that looks more good) than you can changed that also.

**Comment by MayankUjawane** [comment]
![Screenshot (69)](https://user-images.githubusercontent.com/67855648/108252218-3f925400-710d-11eb-83f0-9afd84240f78.png)
Please check this I think this one is better.

**Comment by priyalbhatewara123** [comment]
No , this doesn't go with the pink bg of screenshots .

**Comment by MayankUjawane** [comment]
![Screenshot (71)](https://user-images.githubusercontent.com/67855648/108256433-656e2780-7112-11eb-8cc5-c9d4367a0e64.png)

**Comment by priyalbhatewara123** [comment]
These colors don't go with the theme of the app. So it's better to have white background. 
I made the bg white by myself and text to pink and black. I am closing the issue now.
