### ISSUE TITLE
Add contact page - UI improve

### ISSUE THREAD

**Issue by codeDamon** [priyalbhatewara123/SHE--Live-Without-Fear#35]
The UI of contact add page doesn't looks good.
It can be upgraded as the UI of login and signup screens - by using Material theme EditTexts.

[ Note: There may be better UI upgrades for this screen. One can use their own creativity. ]

**Comment by priyalbhatewara123** [comment]
Agreed @codeDamon .

**Comment by codeDamon** [comment]
Let me solve this issue!
