### ISSUE TITLE
Add a notification in NotificationDrawer to pause and cancel 'Siren'

### ISSUE THREAD

**Issue by codeDamon** [priyalbhatewara123/SHE--Live-Without-Fear#36]
In order to pause/stop the siren, user have to open 'Fake siren' screen. We can have a notification in the NotificationDrawer of the device to pause/stop siren. This will be much convenient for the user.

**Comment by priyalbhatewara123** [comment]
Good one @codeDamon🚀

**Comment by codeDamon** [comment]
Lets solve few issues :)
Assign this to me
