### ISSUE TITLE
Stop button in Fake Siren activity

### ISSUE THREAD

**Issue by priyalbhatewara123** [priyalbhatewara123/SHE--Live-Without-Fear#4]
Stop button doesn't work after switching to different activity.

**Comment by codeDamon** [comment]
I can work on this issue. Please assign it to me.

**Comment by priyalbhatewara123** [comment]
Hey @codeDamon ! Are you a part of JWOC?

**Comment by codeDamon** [comment]
Yes, I am.

**Comment by priyalbhatewara123** [comment]
Great! Assigning you👍
Also provide me your discord username.

**Comment by codeDamon** [comment]
> Great! Assigning you+1
> Also provide me your discord username.

Discord Username: Ash-365

**Comment by codeDamon** [comment]
> Stop button doesn't work after switching to different activity.

Reason for that:
* Every time 'siren' Activity loads the 'player'(MusicPlayer) becomes null.

How to solve: (According to me)
* We have to store this player instance in a SharedPreference using Gson Library ([Refer](https://stackoverflow.com/questions/7145606/how-do-you-save-store-objects-in-sharedpreferences-on-android))
* When the 'siren' activity loads, we check this SharedPreference and perform operations accordingly.

Should I proceed with this way or any other better way?

**Comment by priyalbhatewara123** [comment]
> > Stop button doesn't work after switching to different activity.
> 
> Reason for that:
> 
> * Every time 'siren' Activity loads the 'player'(MusicPlayer) becomes null.
> 
> How to solve: (According to me)
> 
> * We have to store this player instance in a SharedPreference using Gson Library ([Refer](https://stackoverflow.com/questions/7145606/how-do-you-save-store-objects-in-sharedpreferences-on-android))
> * When the 'siren' activity loads, we check this SharedPreference and perform operations accordingly.
> 
> Should I proceed with this way or any other better way?

You can proceed this way only. 
Please make sure you don't make a PR from master branch.

**Comment by codeDamon** [comment]
> > > Stop button doesn't work after switching to different activity.
> > 
> > 
> > Reason for that:
> > 
> > * Every time 'siren' Activity loads the 'player'(MusicPlayer) becomes null.
> > 
> > How to solve: (According to me)
> > 
> > * We have to store this player instance in a SharedPreference using Gson Library ([Refer](https://stackoverflow.com/questions/7145606/how-do-you-save-store-objects-in-sharedpreferences-on-android))
> > * When the 'siren' activity loads, we check this SharedPreference and perform operations accordingly.
> > 
> > Should I proceed with this way or any other better way?
> 
> You can proceed this way only.
> Please make sure you don't make a PR from master branch.

Okay
Ya, sure.

**Comment by codeDamon** [comment]
Found a better way - Using **Singleton Class** :+1:
