### ISSUE TITLE
Sort the Contact List

### ISSUE THREAD

**Issue by MayankUjawane** [priyalbhatewara123/SHE--Live-Without-Fear#46]
The contacts appear on the list view are not sorted. Make it sorted by name.
![Screenshot (78)](https://user-images.githubusercontent.com/67855648/108478694-acab0400-7249-11eb-82fe-a5cd2e0bcba5.png)

**Comment by priyalbhatewara123** [comment]
Good one @MayankUjawane 
Will you work on this ?

**Comment by MayankUjawane** [comment]
Sure Ma'am

**Comment by priyalbhatewara123** [comment]
> Sure Ma'am

Today is the last day of Phase 2. So try to make a PR by today itself.

**Comment by MayankUjawane** [comment]
Sure Ma'am. 
I will make a PR today only.
