### ISSUE TITLE
Enhance the UI of Fake Siren Activity.

### ISSUE THREAD

**Issue by priyalbhatewara123** [priyalbhatewara123/SHE--Live-Without-Fear#5]

**Comment by MayankUjawane** [comment]
I would like to work on this issue.

**Comment by priyalbhatewara123** [comment]
Sure! Send screenshots first☺

**Comment by MayankUjawane** [comment]
Ma'am I think we should not display both stop and play button at the same time, because unless and until we did not play siren there is no requirement of stop button and when we played the song then there is no requirement of play button, so I think we should display play button first and when siren started then we will display stop button. Please give your valuable suggestions.

**Comment by MayankUjawane** [comment]
![Screenshot (18)](https://user-images.githubusercontent.com/67855648/106447834-cfaa7b00-6436-11eb-9de0-deea95921ca9.png)
![Screenshot (20)](https://user-images.githubusercontent.com/67855648/106447852-d33e0200-6436-11eb-8144-a294bf495e65.png)
Please review these designs.

**Comment by priyalbhatewara123** [comment]
So like we'll have 2 different activities or dynamically it will change? @MayankUjawane

**Comment by MayankUjawane** [comment]
No Ma'am we will use the Visibility. Initially the visibility of stop button will be gone and when the play button is clicked then we will set visibility of play button gone and visibility of stop button visible in this way there will be only one button visible at a time.

**Comment by priyalbhatewara123** [comment]
Okay! just make sure that backend functioning don't get affected.

**Comment by priyalbhatewara123** [comment]
Don't keep the background black. It doesn't look good

**Comment by MayankUjawane** [comment]
Yes Ma'am backend will not get affected.
Ma'am please suggest the color for background.

**Comment by priyalbhatewara123** [comment]
Background can be white

**Comment by MayankUjawane** [comment]
ok

**Comment by MayankUjawane** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/67855648/106480999-d4842480-6460-11eb-8772-11782de0eedd.png)
![Screenshot (24)](https://user-images.githubusercontent.com/67855648/106481031-dfd75000-6460-11eb-81ea-a7099a84e2b5.png)

**Comment by MayankUjawane** [comment]
![Screenshot (26)](https://user-images.githubusercontent.com/67855648/106481156-00070f00-6461-11eb-92fd-25cbc4d968a5.png)

**Comment by MayankUjawane** [comment]
Ma'am which one is better White or offWhite

**Comment by priyalbhatewara123** [comment]
Can you please reduce the size of play and stop button and size of pink card also.

**Comment by priyalbhatewara123** [comment]
> Ma'am which one is better White or offWhite

White because other activity also has white bg

**Comment by MayankUjawane** [comment]
Ok I will do this.

**Comment by MayankUjawane** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/67855648/106486061-1bc0e400-6466-11eb-92f1-396d6a086ff0.png)
![Screenshot (30)](https://user-images.githubusercontent.com/67855648/106486075-1e233e00-6466-11eb-8595-b5c37cb6b93a.png)

**Comment by MayankUjawane** [comment]
The backend is also working properly.

**Comment by priyalbhatewara123** [comment]
Great! You can make a PR then✨

**Comment by MayankUjawane** [comment]
Ok Ma'am
