### ISSUE TITLE
Change  list view of emergency contacts.

### ISSUE THREAD

**Issue by priyalbhatewara123** [priyalbhatewara123/SHE--Live-Without-Fear#8]

**Comment by MayankUjawane** [comment]
Ma'am I am not able to understand this issue. What we have to do in this ??

**Comment by codeDamon** [comment]
Did you want to change the look of the list or convert ListView to RecyclerView or anything else? 
Please specify that.

**Comment by codeDamon** [comment]
Once it will be clear - if @MayankUjawane want to work on this issue, assign him otherwise i am ready :+1:

**Comment by priyalbhatewara123** [comment]
Currently contacts UI looks like this👇

<img src="https://user-images.githubusercontent.com/47683250/106365627-d5339280-635c-11eb-9490-1b70613fdbbd.png" width = "200">

It can be modified as👇
[ Note: This is my suggestion. You can use your own creativity. If you have any other idea do send them here✨]
<img src = "https://user-images.githubusercontent.com/47683250/106366094-a539be80-635f-11eb-9d69-8e4369384d43.png" width = "300">

SQLite is used to store the contacts locally on user's device. You can change the list view to recycler view.
Only the UI part should be done under this issue. Backend work for edit and delete option will be done under different issue which I'll create after completing the UI part.

**Comment by priyalbhatewara123** [comment]
@codeDamon let me know if you have any other doubts. Otherwise I'll assign it to you✔

**Comment by codeDamon** [comment]
No now i don't have any doubts. As @MayankUjawane asked previously, if he still wants to work on this issue you should assign him first. 
Lets wait for couple of days for his response.

**Comment by priyalbhatewara123** [comment]
> No now i don't have any doubts. As @MayankUjawane asked previously, if he still wants to work on this issue you should assign him first.
> Lets wait for couple of days for his response.

I explained him long back on slack. I don't thing he wish to take up this issue otherwise he would have commented

**Comment by codeDamon** [comment]
Okay, assign this issue to me then :+1:
