### ISSUE TITLE
Google authorisation for sign up.

### ISSUE THREAD

**Issue by mahmood199** [priyalbhatewara123/SHE--Live-Without-Fear#9]

**Comment by mahmood199** [comment]
The user needs to provide a an email address. We will use this for real time location tracking using Google Maps API

**Comment by priyalbhatewara123** [comment]
> The user needs to provide a an email address. We will use this for real time location tracking using Google Maps API

Please explain the issue in detail. Like what advantages it would give over the API used currently?
